# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: deploy #0. GitHub Action에서 보여질 이름을 지정한다.

on:
  release:
    types: [push] #1. push 시 자동으로 실행된다.
  push:
    branches: [master] #2. master 브랜치에서 동작한다.
  workflow_dispatch:   #3. 수동으로도 실행이 가능하다.

jobs:
  build:
    runs-on: ubuntu-latest #4. 해당 스크립트를 작동할 OS
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3 #5. 프로젝트 코드를 CheckOut한다.
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3 #6. Java 11 버전을 설치한다.
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew #7. gradle wrapper를 실행할 수 있도록 실행 권한을 부여한다.
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test #8. gradle wrapper를 통해 해당 프로젝트를 build한다.
      shell: bash
